workflows:
  my-workflow:
    scripts:
      - name: Run iOS tests
        script: |
          set -e # exit on first failed command

          xcodebuild clean build test -workspace gamingsimpleclean.xcodeproj/project.xcworkspace -scheme "gamingsimpleclean" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.1,name=iPhone 12" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO